version: '3.9'

networks:
  appnet:

services:
  
  mysqldb:
    build: ./mysql
    ports:
     - '3306:3306'
    networks:
      - appnet
  
  app:
    restart: on-failure
    build: ./app
    ports:
      - '8081:5000'
    networks:
      - appnet
    depends_on:
      - mysqldb
    links:
      - mysqldb
    
  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    networks:
      - appnet
    depends_on:
     - app